=== ArgentAlisXI/apuntes-html-css-xml/Lenguaje de Marcas/XML/2 Validación de documentos XML/Ejercicio 7/comunidades.dtd
<!ELEMENT comunidades (comunidad+)>
    <!ELEMENT comunidad (presidente, diaComunidad, provincias)>
    <!ATTLIST comunidad
        codigo CDATA #REQUIRED
        nombre CDATA #REQUIRED>
    <!ELEMENT presidente (#PCDATA)>
    <!ELEMENT diaComunidad EMPTY>
    <!ATTLIST diaComunidad
        dia CDATA #REQUIRED
        mes CDATA #REQUIRED>
    <!ELEMENT provincias (provincia+)>

    <!ELEMENT provincia (superficie, capital, localidades)>
    <!ATTLIST provincia
        codigo CDATA #REQUIRED
        nombre CDATA #REQUIRED
        costa (si | no) "si">
    <!ELEMENT superficie (#PCDATA)>
    <!ATTLIST superficie unidad CDATA #REQUIRED>
    <!ELEMENT capital (#PCDATA)>
    <!ELEMENT localidades (localidad+)>

    <!ELEMENT localidad (festivoLocal1, festivoLocal2?)>
    <!ATTLIST localidad
        nombre CDATA #REQUIRED
        habitantes CDATA #REQUIRED>
    <!ELEMENT festivoLocal1 EMPTY>
    <!ATTLIST festivoLocal1
        dia CDATA #REQUIRED
        mes CDATA #REQUIRED
        motivo CDATA #IMPLIED>
    <!ELEMENT festivoLocal2 EMPTY>
    <!ATTLIST festivoLocal2
        dia CDATA #REQUIRED
        mes CDATA #REQUIRED
        motivo CDATA #IMPLIED>

=== ArgentAlisXI/apuntes-html-css-xml/XML/2 Validación de documentos XML/Ejercicio 7/07Correa_Segade_CristinaEjercicio7XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comunidades SYSTEM "comunidades.dtd">
<comunidades>
    <comunidad codigo="GA" nombre="Galicia">
        <presidente>Alberto Núñez Feijóo</presidente>
        <diaComunidad dia="25" mes="07" />
        <provincias>
            <provincia codigo="C" nombre="A Coruña" costa="si">
                <superficie unidad="%km2;">7092</superficie>
                <capital>A Coruña</capital>
                <localidades>
                    <localidad nombre="A Coruña" habitantes="246056">
                        <festivoLocal1 dia="17" mes="05" motivo="Día das Letras Galegas" />
                        <festivoLocal2 dia="16" mes="08" />
                    </localidad>
                    <localidad nombre="Ferrol" habitantes="67152">
                        <festivoLocal1 dia="24" mes="06" />
                        <festivoLocal2 dia="08" mes="09" />
                    </localidad>
                </localidades>
            </provincia>
            <provincia codigo="LU" nombre="Lugo" costa="no">
                <superficie unidad="%km2;">9856</superficie>
                <capital>Lugo</capital>
                <localidades>
                    <localidad nombre="Lugo" habitantes="97516">
                        <festivoLocal1 dia="17" mes="05" motivo="Día das Letras Galegas" />
                        <festivoLocal2 dia="08" mes="09" />
                    </localidad>
                    <localidad nombre="Vilalba" habitantes="15159">
                        <festivoLocal1 dia="08" mes="09" />
                        <festivoLocal2 dia="14" mes="09" />
                    </localidad>
                </localidades>
            </provincia>
            <provincia codigo="O" nombre="Ourense" costa="no">
                <superficie unidad="%km2;">7273</superficie>
                <capital>Ourense</capital>
                <localidades>
                    <localidad nombre="Ourense" habitantes="105919">
                        <festivoLocal1 dia="17" mes="05" motivo="Día das Letras Galegas" />
                        <festivoLocal2 dia="01" mes="10" />
                    </localidad>
                    <localidad nombre="Verín" habitantes="14031">
                        <festivoLocal1 dia="05" mes="08" />
                        <festivoLocal2 dia="07" mes="10" />
                    </localidad>
                </localidades>
            </provincia>
        </provincias>
    </comunidad>
</comunidades>
